/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package youtubedownloader;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   // TODO: Add tests
}
